import { Question } from '../types';

export const mathQuestions: Question[] = [
    // === ALJABAR LINEAR ===
    {
        id: 'math-01',
        type: 'multiple-choice',
        question: 'Tentukan nilai x dari persamaan 2x + 6 = 14',
        options: ['2', '4', '6', '8'],
        answer: '4',
        explanation: '2x + 6 = 14 → 2x = 8 → x = 4',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-02',
        type: 'type-answer',
        question: 'Jika 3x − 5 = 16, berapakah nilai x?',
        answer: '7',
        explanation: '3x − 5 = 16 → 3x = 21 → x = 7',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-03',
        type: 'true-false',
        question: 'Persamaan 5x − 3 = 2x + 9 memiliki solusi x = 4',
        answer: 'true',
        explanation: '5(4) − 3 = 17 dan 2(4) + 9 = 17. Kedua ruas sama, jadi benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-04',
        type: 'drag-drop',
        question: 'Pasangkan persamaan dengan solusinya:',
        pairs: [
            { left: 'x + 5 = 12', right: 'x = 7' },
            { left: '2x = 18', right: 'x = 9' },
            { left: 'x − 3 = 10', right: 'x = 13' },
        ],
        answer: ['x + 5 = 12::x = 7', '2x = 18::x = 9', 'x − 3 = 10::x = 13'],
        explanation: 'Selesaikan masing-masing persamaan linear satu variabel.',
        points: 15,
        difficulty: 'medium',
    },

    // === FUNGSI KUADRAT ===
    {
        id: 'math-05',
        type: 'multiple-choice',
        question: 'Akar-akar dari x² − 5x + 6 = 0 adalah ...',
        options: ['x = 2 dan x = 3', 'x = 1 dan x = 6', 'x = −2 dan x = −3', 'x = −1 dan x = −6'],
        answer: 'x = 2 dan x = 3',
        explanation: 'x² − 5x + 6 = (x − 2)(x − 3) = 0, maka x = 2 atau x = 3.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-06',
        type: 'type-answer',
        question: 'Tentukan diskriminan dari persamaan x² + 4x + 4 = 0',
        answer: '0',
        explanation: 'D = b² − 4ac = 16 − 16 = 0. Persamaan memiliki akar kembar.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-07',
        type: 'true-false',
        question: 'Grafik fungsi f(x) = x² − 4 memotong sumbu-x di titik (2, 0) dan (−2, 0)',
        answer: 'true',
        explanation: 'x² − 4 = 0 → x² = 4 → x = ±2. Jadi memotong sumbu-x di (2,0) dan (−2,0).',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-08',
        type: 'multiple-choice',
        question: 'Titik puncak parabola y = x² − 6x + 5 adalah ...',
        options: ['(3, −4)', '(3, 4)', '(−3, −4)', '(6, 5)'],
        answer: '(3, −4)',
        explanation: 'xp = −b/2a = 6/2 = 3, yp = 9 − 18 + 5 = −4. Titik puncak = (3, −4).',
        points: 15,
        difficulty: 'medium',
    },

    // === TRIGONOMETRI ===
    {
        id: 'math-09',
        type: 'multiple-choice',
        question: 'Nilai dari sin 30° adalah ...',
        options: ['1/2', '√2/2', '√3/2', '1'],
        answer: '1/2',
        explanation: 'sin 30° = 1/2 merupakan nilai trigonometri sudut istimewa.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-10',
        type: 'type-answer',
        question: 'Berapa nilai cos 60° ? (jawab dalam pecahan sederhana, contoh: 1/2)',
        answer: '1/2',
        explanation: 'cos 60° = 1/2 merupakan sudut istimewa trigonometri.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-11',
        type: 'true-false',
        question: 'tan 45° = 1',
        answer: 'true',
        explanation: 'tan 45° = sin 45° / cos 45° = (√2/2) / (√2/2) = 1.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-12',
        type: 'drag-drop',
        question: 'Pasangkan fungsi trigonometri dengan nilainya:',
        pairs: [
            { left: 'sin 90°', right: '1' },
            { left: 'cos 0°', right: '1' },
            { left: 'tan 0°', right: '0' },
        ],
        answer: ['sin 90°::1', 'cos 0°::1', 'tan 0°::0'],
        explanation: 'sin 90° = 1, cos 0° = 1, tan 0° = 0.',
        points: 15,
        difficulty: 'medium',
    },

    // === PELUANG ===
    {
        id: 'math-13',
        type: 'multiple-choice',
        question: 'Sebuah dadu dilempar sekali. Peluang muncul angka genap adalah ...',
        options: ['1/2', '1/3', '1/6', '2/3'],
        answer: '1/2',
        explanation: 'Angka genap = {2, 4, 6}, ada 3 dari 6 kemungkinan. P = 3/6 = 1/2.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-14',
        type: 'type-answer',
        question: 'Sebuah koin dilempar 2 kali. Berapa banyak ruang sampel? (jawab angka)',
        answer: '4',
        explanation: 'Ruang sampel = {AA, AG, GA, GG} = 4 kejadian.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-15',
        type: 'true-false',
        question: 'Peluang suatu kejadian selalu bernilai antara 0 dan 1 (inklusif)',
        answer: 'true',
        explanation: '0 ≤ P(A) ≤ 1 untuk setiap kejadian A.',
        points: 10,
        difficulty: 'easy',
    },

    // === STATISTIKA ===
    {
        id: 'math-16',
        type: 'multiple-choice',
        question: 'Rata-rata dari data 4, 6, 8, 10, 12 adalah ...',
        options: ['8', '7', '9', '10'],
        answer: '8',
        explanation: 'Rata-rata = (4+6+8+10+12)/5 = 40/5 = 8.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-17',
        type: 'type-answer',
        question: 'Tentukan median dari data: 3, 7, 2, 9, 5',
        answer: '5',
        explanation: 'Urutkan: 2, 3, 5, 7, 9. Median (nilai tengah) = 5.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-18',
        type: 'true-false',
        question: 'Modus dari data 2, 3, 3, 5, 7, 7, 7 adalah 3',
        answer: 'false',
        explanation: 'Modus adalah data yang paling sering muncul, yaitu 7 (muncul 3 kali).',
        points: 10,
        difficulty: 'easy',
    },

    // === LIMIT DASAR ===
    {
        id: 'math-19',
        type: 'multiple-choice',
        question: 'Nilai dari lim(x→2) (x² − 4)/(x − 2) adalah ...',
        options: ['4', '2', '0', 'Tidak ada'],
        answer: '4',
        explanation: 'Faktorkan: (x²−4)/(x−2) = (x+2)(x−2)/(x−2) = x+2. Substitusi x=2: 2+2 = 4.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-20',
        type: 'type-answer',
        question: 'Tentukan nilai lim(x→3) (2x + 1)',
        answer: '7',
        explanation: 'Substitusi langsung: 2(3) + 1 = 7.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-21',
        type: 'multiple-choice',
        question: 'Nilai lim(x→0) (sin x)/x adalah ...',
        options: ['1', '0', '∞', 'Tidak ada'],
        answer: '1',
        explanation: 'Ini adalah limit trigonometri dasar: lim(x→0) sin(x)/x = 1.',
        points: 20,
        difficulty: 'hard',
    },
    {
        id: 'math-22',
        type: 'drag-drop',
        question: 'Pasangkan limit dengan hasilnya:',
        pairs: [
            { left: 'lim(x→1) x²', right: '1' },
            { left: 'lim(x→0) (x+5)', right: '5' },
            { left: 'lim(x→4) √x', right: '2' },
        ],
        answer: ['lim(x→1) x²::1', 'lim(x→0) (x+5)::5', 'lim(x→4) √x::2'],
        explanation: 'Substitusi langsung pada masing-masing fungsi.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-23',
        type: 'true-false',
        question: 'lim(x→∞) 1/x = 0',
        answer: 'true',
        explanation: 'Ketika x mendekati tak hingga, 1/x mendekati 0.',
        points: 15,
        difficulty: 'medium',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 1: ALJABAR LINEAR (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'math-a01',
        type: 'multiple-choice',
        question: 'Nilai x yang memenuhi 4x − 8 = 0 adalah ...',
        options: ['1', '2', '4', '8'],
        answer: '2',
        explanation: '4x − 8 = 0 → 4x = 8 → x = 2.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a02',
        type: 'type-answer',
        question: 'Berapakah x jika 7x = 56?',
        answer: '8',
        explanation: 'x = 56 ÷ 7 = 8.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a03',
        type: 'true-false',
        question: 'Penyelesaian dari 2x + 3 > 9 adalah x > 3',
        answer: 'true',
        explanation: '2x + 3 > 9 → 2x > 6 → x > 3. Benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a04',
        type: 'multiple-choice',
        question: 'Jika 5(x − 2) = 15, maka x = ...',
        options: ['3', '5', '7', '10'],
        answer: '5',
        explanation: '5(x − 2) = 15 → x − 2 = 3 → x = 5.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a05',
        type: 'type-answer',
        question: 'Himpunan penyelesaian dari x/3 = 5 adalah x = ...',
        answer: '15',
        explanation: 'x = 5 × 3 = 15.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a06',
        type: 'true-false',
        question: 'Nilai x = −2 memenuhi persamaan 3x + 6 = 0',
        answer: 'true',
        explanation: '3(−2) + 6 = −6 + 6 = 0. Benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a07',
        type: 'multiple-choice',
        question: 'Pertidaksamaan −3x + 1 ≤ 10 diselesaikan oleh ...',
        options: ['x ≥ −3', 'x ≤ −3', 'x ≥ 3', 'x ≤ 3'],
        answer: 'x ≥ −3',
        explanation: '−3x + 1 ≤ 10 → −3x ≤ 9 → x ≥ −3 (tanda berubah karena dibagi bilangan negatif).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-a08',
        type: 'type-answer',
        question: 'Jika 2x + y = 10 dan x = 3, maka y = ...',
        answer: '4',
        explanation: '2(3) + y = 10 → 6 + y = 10 → y = 4.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a09',
        type: 'multiple-choice',
        question: 'Solusi SPLDV: x + y = 7 dan x − y = 3 adalah ...',
        options: ['x=5, y=2', 'x=4, y=3', 'x=2, y=5', 'x=3, y=4'],
        answer: 'x=5, y=2',
        explanation: 'Tambahkan: 2x = 10 → x = 5. Lalu y = 7 − 5 = 2.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-a10',
        type: 'true-false',
        question: 'Persamaan 6x − 4 = 2x + 8 memiliki solusi x = 3',
        answer: 'true',
        explanation: '6(3) − 4 = 14 dan 2(3) + 8 = 14. Kedua ruas sama → benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-a11',
        type: 'multiple-choice',
        question: 'Himpunan penyelesaian dari |x − 3| = 5 adalah ...',
        options: ['{8, −2}', '{8, 2}', '{−8, 2}', '{−8, −2}'],
        answer: '{8, −2}',
        explanation: '|x − 3| = 5 → x − 3 = 5 atau x − 3 = −5 → x = 8 atau x = −2.',
        points: 20,
        difficulty: 'hard',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 2: FUNGSI KUADRAT (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'math-b01',
        type: 'multiple-choice',
        question: 'Nilai diskriminan dari x² + 6x + 9 = 0 adalah ...',
        options: ['0', '−9', '9', '36'],
        answer: '0',
        explanation: 'D = b² − 4ac = 36 − 36 = 0. Persamaan memiliki akar kembar.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b02',
        type: 'type-answer',
        question: 'Jika f(x) = x² − 9, maka f(3) = ...',
        answer: '0',
        explanation: 'f(3) = 9 − 9 = 0.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-b03',
        type: 'true-false',
        question: 'Parabola y = −x² + 4 membuka ke bawah',
        answer: 'true',
        explanation: 'Koefisien a = −1 < 0, sehingga parabola membuka ke bawah.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-b04',
        type: 'multiple-choice',
        question: 'Akar-akar dari x² + x − 6 = 0 adalah ...',
        options: ['x = 2 dan x = −3', 'x = −2 dan x = 3', 'x = 1 dan x = −6', 'x = 3 dan x = 2'],
        answer: 'x = 2 dan x = −3',
        explanation: 'x² + x − 6 = (x + 3)(x − 2) = 0 → x = −3 atau x = 2.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b05',
        type: 'type-answer',
        question: 'Titik puncak dari y = x² − 2x + 5 memiliki nilai minimum y = ...',
        answer: '4',
        explanation: 'xp = −(−2)/(2×1) = 1, yp = 1 − 2 + 5 = 4.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b06',
        type: 'true-false',
        question: 'Persamaan x² + 4x + 5 = 0 tidak memiliki akar real',
        answer: 'true',
        explanation: 'D = 16 − 20 = −4 < 0, sehingga tidak ada akar real.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b07',
        type: 'multiple-choice',
        question: 'Grafik y = x² bergeser 3 ke kanan menjadi ...',
        options: ['y = (x−3)²', 'y = (x+3)²', 'y = x² − 3', 'y = x² + 3'],
        answer: 'y = (x−3)²',
        explanation: 'Pergeseran horizontal ke kanan k satuan: y = (x − k)².',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b08',
        type: 'type-answer',
        question: 'Jumlah akar-akar persamaan 2x² − 6x + 4 = 0 adalah ...',
        answer: '3',
        explanation: 'Jumlah akar = −b/a = 6/2 = 3 (rumus Vieta).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b09',
        type: 'multiple-choice',
        question: 'Hasil kali akar-akar dari 3x² − 9x + 6 = 0 adalah ...',
        options: ['2', '3', '−2', '6'],
        answer: '2',
        explanation: 'Hasil kali akar = c/a = 6/3 = 2 (rumus Vieta).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-b10',
        type: 'true-false',
        question: 'Fungsi y = 2x² + 3x − 2 memiliki nilai minimum (karena a > 0)',
        answer: 'true',
        explanation: 'Karena a = 2 > 0, parabola membuka ke atas dan memiliki nilai minimum.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-b11',
        type: 'multiple-choice',
        question: 'Berapa banyak titik potong x² + 2x + 1 = 0 dengan sumbu-x?',
        options: ['1 titik', '2 titik', '0 titik', 'Tak terhingga'],
        answer: '1 titik',
        explanation: 'D = 4 − 4 = 0, berarti ada tepat 1 titik potong (akar kembar).',
        points: 15,
        difficulty: 'medium',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 3: TRIGONOMETRI (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'math-c01',
        type: 'multiple-choice',
        question: 'Nilai dari cos 30° adalah ...',
        options: ['√3/2', '1/2', '√2/2', '1'],
        answer: '√3/2',
        explanation: 'cos 30° = √3/2 adalah nilai trigonometri sudut istimewa.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c02',
        type: 'type-answer',
        question: 'Berapa nilai sin 0°? (jawab angka bulat)',
        answer: '0',
        explanation: 'sin 0° = 0 merupakan sudut istimewa trigonometri.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c03',
        type: 'true-false',
        question: 'sin² θ + cos² θ = 1 untuk semua nilai θ',
        answer: 'true',
        explanation: 'Ini adalah identitas Pythagoras trigonometri yang selalu berlaku.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c04',
        type: 'multiple-choice',
        question: 'Nilai tan 30° adalah ...',
        options: ['1/√3', '√3', '1', '1/2'],
        answer: '1/√3',
        explanation: 'tan 30° = sin 30° / cos 30° = (1/2)/(√3/2) = 1/√3.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-c05',
        type: 'type-answer',
        question: 'Berapa nilai cos 90°? (jawab angka bulat)',
        answer: '0',
        explanation: 'cos 90° = 0 merupakan sudut istimewa trigonometri.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c06',
        type: 'true-false',
        question: 'sin 60° > sin 30°',
        answer: 'true',
        explanation: 'sin 60° = √3/2 ≈ 0.866, sin 30° = 0.5. Jadi sin 60° > sin 30°.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c07',
        type: 'multiple-choice',
        question: 'Nilai sin 45° adalah ...',
        options: ['√2/2', '√3/2', '1/2', '1'],
        answer: '√2/2',
        explanation: 'sin 45° = cos 45° = √2/2 merupakan nilai sudut istimewa.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c08',
        type: 'multiple-choice',
        question: 'Dalam segitiga siku-siku, jika sin α = 3/5, maka cos α = ...',
        options: ['4/5', '3/4', '5/3', '5/4'],
        answer: '4/5',
        explanation: 'sin²α + cos²α = 1 → (3/5)² + cos²α = 1 → cos²α = 16/25 → cos α = 4/5.',
        points: 20,
        difficulty: 'hard',
    },
    {
        id: 'math-c09',
        type: 'true-false',
        question: 'Nilai cos 0° = 1',
        answer: 'true',
        explanation: 'cos 0° = 1 adalah salah satu sudut istimewa trigonometri.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-c10',
        type: 'multiple-choice',
        question: 'Konversi 180° ke radian adalah ...',
        options: ['π', '2π', 'π/2', 'π/4'],
        answer: 'π',
        explanation: '180° = π radian. Ini adalah konversi dasar derajat ke radian.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-c11',
        type: 'type-answer',
        question: 'tan 60° = √3 atau 1/√3? Jawab: √3 atau 1/√3',
        answer: '√3',
        explanation: 'tan 60° = sin 60°/cos 60° = (√3/2)/(1/2) = √3.',
        points: 15,
        difficulty: 'medium',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 4: PELUANG & STATISTIKA (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'math-d01',
        type: 'multiple-choice',
        question: 'Sebuah kartu diambil acak dari 52 kartu bridge. Peluang mendapat kartu As adalah ...',
        options: ['1/13', '1/4', '1/52', '4/52'],
        answer: '1/13',
        explanation: 'Ada 4 kartu As dari 52 kartu. P = 4/52 = 1/13.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-d02',
        type: 'type-answer',
        question: 'Rata-rata dari 10, 20, 30, 40, 50 adalah ...',
        answer: '30',
        explanation: 'Rata-rata = (10+20+30+40+50)/5 = 150/5 = 30.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-d03',
        type: 'true-false',
        question: 'Jika sebuah dadu dilempar, peluang muncul angka lebih dari 4 adalah 1/3',
        answer: 'true',
        explanation: 'Angka > 4 = {5, 6}, ada 2 dari 6 kemungkinan. P = 2/6 = 1/3.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-d04',
        type: 'multiple-choice',
        question: 'Modus dari data 5, 3, 5, 7, 5, 9, 3 adalah ...',
        options: ['5', '3', '7', '9'],
        answer: '5',
        explanation: 'Modus adalah nilai yang paling sering muncul. Angka 5 muncul 3 kali.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-d05',
        type: 'type-answer',
        question: 'Median dari data 1, 3, 5, 7, 9, 11 adalah ...',
        answer: '6',
        explanation: 'Data genap (6 nilai): median = (5+7)/2 = 6.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-d06',
        type: 'multiple-choice',
        question: 'Dalam percobaan 2 koin, peluang keduanya muncul gambar adalah ...',
        options: ['1/4', '1/2', '3/4', '1'],
        answer: '1/4',
        explanation: 'Ruang sampel = {AA, AG, GA, GG}. P(GG) = 1/4.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-d07',
        type: 'true-false',
        question: 'Jangkauan (range) dari data 4, 8, 2, 15, 6 adalah 13',
        answer: 'true',
        explanation: 'Jangkauan = nilai max − nilai min = 15 − 2 = 13.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-d08',
        type: 'multiple-choice',
        question: 'Dari 10 siswa, 6 suka Matematika dan 4 suka PPKn. Peluang seorang dipilih acak suka Matematika adalah ...',
        options: ['3/5', '2/5', '1/5', '3/10'],
        answer: '3/5',
        explanation: 'P = 6/10 = 3/5.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-d09',
        type: 'type-answer',
        question: 'Nilai kuartil bawah (Q1) dari data 2, 4, 6, 8, 10, 12 adalah ...',
        answer: '4',
        explanation: 'Q1 adalah median dari paruh bawah {2, 4, 6} = 4.',
        points: 20,
        difficulty: 'hard',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 5: LIMIT (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'math-e01',
        type: 'multiple-choice',
        question: 'Nilai lim(x→1) (x² − 1)/(x − 1) adalah ...',
        options: ['2', '1', '0', 'Tidak ada'],
        answer: '2',
        explanation: 'Faktorkan: (x−1)(x+1)/(x−1) = x+1. Substitusi x=1: 1+1 = 2.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-e02',
        type: 'type-answer',
        question: 'Nilai lim(x→5) (3x − 1) adalah ...',
        answer: '14',
        explanation: 'Substitusi langsung: 3(5) − 1 = 14.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-e03',
        type: 'true-false',
        question: 'lim(x→2) (x² + 1) = 5',
        answer: 'true',
        explanation: 'Substitusi: (2²) + 1 = 4 + 1 = 5. Benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-e04',
        type: 'multiple-choice',
        question: 'lim(x→0) (x³ + 2x)/x = ...',
        options: ['2', '0', '1', 'Tidak ada'],
        answer: '2',
        explanation: '(x³ + 2x)/x = x² + 2. Substitusi x = 0: 0 + 2 = 2.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'math-e05',
        type: 'true-false',
        question: 'lim(x→1) x⁴ = 1',
        answer: 'true',
        explanation: 'Substitusi langsung: 1⁴ = 1. Benar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-e06',
        type: 'multiple-choice',
        question: 'lim(x→∞) (2x + 3)/(x + 1) = ...',
        options: ['2', '3', '1', '∞'],
        answer: '2',
        explanation: 'Bagi pembilang dan penyebut dengan x: (2 + 3/x)/(1 + 1/x) → 2/1 = 2.',
        points: 20,
        difficulty: 'hard',
    },
    {
        id: 'math-e07',
        type: 'type-answer',
        question: 'Nilai lim(x→4) √x adalah ...',
        answer: '2',
        explanation: 'Substitusi: √4 = 2.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'math-e08',
        type: 'multiple-choice',
        question: 'lim(x→−∞) (x² + x)/(2x²) = ...',
        options: ['1/2', '1', '0', '2'],
        answer: '1/2',
        explanation: 'Bagi dengan x²: (1 + 1/x)/2 → 1/2 saat x→−∞.',
        points: 20,
        difficulty: 'hard',
    },
    {
        id: 'math-e09',
        type: 'true-false',
        question: 'Jika f(x) = 5, maka lim(x→100) f(x) = 5',
        answer: 'true',
        explanation: 'Fungsi konstan f(x) = 5 selalu bernilai 5, sehingga limitnya 5.',
        points: 10,
        difficulty: 'easy',
    },
];
