import { Question } from '../types';

export const pknQuestions: Question[] = [
    // === PANCASILA & IMPLEMENTASINYA ===
    {
        id: 'pkn-01',
        type: 'multiple-choice',
        question: 'Bunyi sila kedua Pancasila adalah ...',
        options: [
            'Kemanusiaan yang adil dan beradab',
            'Persatuan Indonesia',
            'Ketuhanan Yang Maha Esa',
            'Keadilan sosial bagi seluruh rakyat Indonesia',
        ],
        answer: 'Kemanusiaan yang adil dan beradab',
        explanation: 'Sila kedua Pancasila berbunyi "Kemanusiaan yang adil dan beradab" yang menekankan pengakuan HAM.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-02',
        type: 'drag-drop',
        question: 'Pasangkan sila Pancasila dengan lambangnya:',
        pairs: [
            { left: 'Sila ke-1', right: 'Bintang' },
            { left: 'Sila ke-2', right: 'Rantai' },
            { left: 'Sila ke-3', right: 'Pohon Beringin' },
        ],
        answer: ['Sila ke-1::Bintang', 'Sila ke-2::Rantai', 'Sila ke-3::Pohon Beringin'],
        explanation: 'Bintang = Ketuhanan YME, Rantai = Kemanusiaan, Pohon Beringin = Persatuan Indonesia.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-03',
        type: 'true-false',
        question: 'Pancasila ditetapkan sebagai dasar negara pada tanggal 18 Agustus 1945',
        answer: 'true',
        explanation: 'Pancasila disahkan dalam sidang PPKI tanggal 18 Agustus 1945 bersamaan dengan UUD 1945.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-04',
        type: 'type-answer',
        question: 'Siapakah yang pertama kali mengusulkan nama "Pancasila" sebagai dasar negara? (jawab nama belakang)',
        answer: 'Soekarno',
        explanation: 'Ir. Soekarno mengusulkan nama Pancasila pada sidang BPUPKI tanggal 1 Juni 1945.',
        points: 10,
        difficulty: 'easy',
    },

    // === UUD 1945 PASAL PENTING ===
    {
        id: 'pkn-05',
        type: 'multiple-choice',
        question: 'Pasal berapa dalam UUD 1945 yang mengatur tentang hak beragama?',
        options: ['Pasal 29', 'Pasal 27', 'Pasal 31', 'Pasal 33'],
        answer: 'Pasal 29',
        explanation: 'Pasal 29 UUD 1945 mengatur tentang kebebasan beragama dan beribadah.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-06',
        type: 'true-false',
        question: 'Pasal 31 UUD 1945 mengatur tentang hak setiap warga negara untuk mendapat pendidikan',
        answer: 'true',
        explanation: 'Pasal 31 ayat (1): "Setiap warga negara berhak mendapat pendidikan."',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-07',
        type: 'drag-drop',
        question: 'Pasangkan pasal UUD 1945 dengan isinya:',
        pairs: [
            { left: 'Pasal 27', right: 'Persamaan kedudukan di hukum' },
            { left: 'Pasal 28', right: 'Kemerdekaan berserikat' },
            { left: 'Pasal 33', right: 'Perekonomian nasional' },
        ],
        answer: ['Pasal 27::Persamaan kedudukan di hukum', 'Pasal 28::Kemerdekaan berserikat', 'Pasal 33::Perekonomian nasional'],
        explanation: 'Pasal 27 tentang hukum, Pasal 28 tentang berserikat, Pasal 33 tentang ekonomi.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-08',
        type: 'type-answer',
        question: 'UUD 1945 telah mengalami berapa kali amandemen? (jawab angka)',
        answer: '4',
        explanation: 'UUD 1945 diamandemen sebanyak 4 kali: tahun 1999, 2000, 2001, dan 2002.',
        points: 10,
        difficulty: 'easy',
    },

    // === SISTEM PEMERINTAHAN RI ===
    {
        id: 'pkn-09',
        type: 'multiple-choice',
        question: 'Sistem pemerintahan yang dianut Indonesia adalah ...',
        options: ['Presidensial', 'Parlementer', 'Semi-presidensial', 'Monarki konstitusional'],
        answer: 'Presidensial',
        explanation: 'Indonesia menganut sistem presidensial di mana presiden sebagai kepala negara sekaligus kepala pemerintahan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-10',
        type: 'true-false',
        question: 'Dalam sistem presidensial Indonesia, presiden dipilih langsung oleh rakyat',
        answer: 'true',
        explanation: 'Sejak amandemen UUD 1945, presiden dan wakil presiden dipilih secara langsung oleh rakyat melalui pemilu.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-11',
        type: 'multiple-choice',
        question: 'Masa jabatan presiden Indonesia adalah ...',
        options: ['5 tahun', '4 tahun', '6 tahun', '7 tahun'],
        answer: '5 tahun',
        explanation: 'Berdasarkan Pasal 7 UUD 1945, presiden memegang jabatan selama 5 tahun dan dapat dipilih kembali untuk satu kali masa jabatan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-12',
        type: 'type-answer',
        question: 'Apa bentuk negara Indonesia? (jawab satu kata)',
        answer: 'Republik',
        explanation: 'Pasal 1 ayat (1) UUD 1945: "Negara Indonesia ialah Negara Kesatuan yang berbentuk Republik."',
        points: 10,
        difficulty: 'easy',
    },

    // === HAK & KEWAJIBAN WARGA NEGARA ===
    {
        id: 'pkn-13',
        type: 'multiple-choice',
        question: 'Berikut yang merupakan kewajiban warga negara Indonesia menurut UUD 1945, kecuali ...',
        options: [
            'Mendapatkan pekerjaan yang layak',
            'Membela negara',
            'Menaati hukum dan pemerintahan',
            'Membayar pajak',
        ],
        answer: 'Mendapatkan pekerjaan yang layak',
        explanation: 'Mendapatkan pekerjaan yang layak adalah HAK warga negara (Pasal 27 ayat 2), bukan kewajiban.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-14',
        type: 'drag-drop',
        question: 'Klasifikasikan mana yang termasuk hak dan mana kewajiban warga negara:',
        pairs: [
            { left: 'Mendapat pendidikan', right: 'Hak' },
            { left: 'Membela negara', right: 'Kewajiban' },
            { left: 'Membayar pajak', right: 'Kewajiban' },
        ],
        answer: ['Mendapat pendidikan::Hak', 'Membela negara::Kewajiban', 'Membayar pajak::Kewajiban'],
        explanation: 'Pendidikan adalah hak (Pasal 31). Membela negara (Pasal 27 ayat 3) dan membayar pajak (Pasal 23A) adalah kewajiban.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-15',
        type: 'true-false',
        question: 'Setiap warga negara berhak atas pekerjaan dan penghidupan yang layak menurut UUD 1945',
        answer: 'true',
        explanation: 'Pasal 27 ayat (2) UUD 1945 menjamin hak atas pekerjaan dan penghidupan yang layak.',
        points: 10,
        difficulty: 'easy',
    },

    // === DEMOKRASI & PEMILU ===
    {
        id: 'pkn-16',
        type: 'multiple-choice',
        question: 'Asas pemilu di Indonesia dikenal dengan singkatan ...',
        options: ['LUBER JURDIL', 'LUBER JUDIL', 'LUBERJUR DINAS', 'JUJUR ADIL'],
        answer: 'LUBER JURDIL',
        explanation: 'LUBER JURDIL = Langsung, Umum, Bebas, Rahasia, Jujur, dan Adil.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-17',
        type: 'type-answer',
        question: 'Lembaga yang menyelenggarakan pemilu di Indonesia adalah ... (singkatan 3 huruf)',
        answer: 'KPU',
        explanation: 'KPU (Komisi Pemilihan Umum) adalah lembaga yang menyelenggarakan pemilu.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-18',
        type: 'true-false',
        question: 'Indonesia menganut demokrasi Pancasila, bukan demokrasi liberal',
        answer: 'true',
        explanation: 'Indonesia menganut demokrasi Pancasila yang berlandaskan nilai-nilai Pancasila, bukan demokrasi liberal ala Barat.',
        points: 10,
        difficulty: 'easy',
    },

    // === LEMBAGA NEGARA ===
    {
        id: 'pkn-19',
        type: 'multiple-choice',
        question: 'Lembaga negara yang berwenang mengadili pada tingkat kasasi adalah ...',
        options: ['Mahkamah Agung', 'Mahkamah Konstitusi', 'Komisi Yudisial', 'DPR'],
        answer: 'Mahkamah Agung',
        explanation: 'MA berwenang mengadili pada tingkat kasasi dan menguji peraturan perundang-undangan di bawah UU.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-20',
        type: 'drag-drop',
        question: 'Pasangkan lembaga negara dengan fungsinya:',
        pairs: [
            { left: 'DPR', right: 'Legislatif' },
            { left: 'Presiden', right: 'Eksekutif' },
            { left: 'MA', right: 'Yudikatif' },
        ],
        answer: ['DPR::Legislatif', 'Presiden::Eksekutif', 'MA::Yudikatif'],
        explanation: 'DPR = pembuat UU (legislatif), Presiden = pelaksana pemerintahan (eksekutif), MA = pelaksana kekuasaan kehakiman (yudikatif).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-21',
        type: 'type-answer',
        question: 'Lembaga yang berwenang menguji UU terhadap UUD adalah ... (dua kata, singkatan)',
        answer: 'MK',
        explanation: 'Mahkamah Konstitusi (MK) berwenang menguji undang-undang terhadap UUD 1945.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-22',
        type: 'multiple-choice',
        question: 'MPR terdiri dari anggota ...',
        options: [
            'DPR dan DPD',
            'DPR dan BPK',
            'DPD dan MA',
            'DPR dan Presiden',
        ],
        answer: 'DPR dan DPD',
        explanation: 'Pasal 2 ayat (1) UUD 1945: MPR terdiri atas anggota DPR dan anggota DPD.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-23',
        type: 'true-false',
        question: 'BPK (Badan Pemeriksa Keuangan) bertugas memeriksa pengelolaan keuangan negara',
        answer: 'true',
        explanation: 'Pasal 23E UUD 1945: BPK bertugas memeriksa pengelolaan dan tanggung jawab tentang keuangan negara.',
        points: 10,
        difficulty: 'easy',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 1: PANCASILA (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'pkn-a01',
        type: 'multiple-choice',
        question: 'Bunyi sila pertama Pancasila adalah ...',
        options: ['Ketuhanan Yang Maha Esa', 'Kemanusiaan yang adil dan beradab', 'Persatuan Indonesia', 'Kerakyatan yang dipimpin oleh hikmat'],
        answer: 'Ketuhanan Yang Maha Esa',
        explanation: 'Sila pertama Pancasila berbunyi "Ketuhanan Yang Maha Esa" yang dilambangkan dengan bintang.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a02',
        type: 'type-answer',
        question: 'Lambang dari sila ke-5 Pancasila adalah padi dan ... (satu kata)',
        answer: 'kapas',
        explanation: 'Sila ke-5 (Keadilan Sosial bagi Seluruh Rakyat Indonesia) dilambangkan dengan padi dan kapas.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a03',
        type: 'true-false',
        question: 'BPUPKI dibentuk sebelum PPKI dalam proses lahirnya Pancasila',
        answer: 'true',
        explanation: 'BPUPKI dibentuk 1 Maret 1945, sedangkan PPKI dibentuk setelah BPUPKI resmi dibubarkan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a04',
        type: 'multiple-choice',
        question: 'Pancasila sebagai pandangan hidup bangsa artinya ...',
        options: ['Menjadi pedoman dalam kehidupan sehari-hari', 'Hanya berlaku di bidang hukum', 'Dasar negara dalam UUD', 'Ideologi komunis'],
        answer: 'Menjadi pedoman dalam kehidupan sehari-hari',
        explanation: 'Pancasila sebagai pandangan hidup berarti ia menjadi pedoman dan acuan dalam kehidupan berbangsa dan bernegara.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a05',
        type: 'true-false',
        question: 'Sila ke-3 Pancasila dilambangkan dengan pohon beringin',
        answer: 'true',
        explanation: 'Sila ke-3 "Persatuan Indonesia" dilambangkan dengan pohon beringin yang bermakna persatuan dan kesatuan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a06',
        type: 'multiple-choice',
        question: 'Sidang BPUPKI pertama membahas tentang ...',
        options: ['Dasar negara', 'Wilayah negara', 'Pemilihan presiden', 'Sistem ekonomi'],
        answer: 'Dasar negara',
        explanation: 'Sidang BPUPKI pertama (29 Mei–1 Juni 1945) membahas tentang dasar negara Indonesia.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a07',
        type: 'type-answer',
        question: 'Pancasila dirumuskan dalam sidang BPUPKI yang dilaksanakan pada tahun ... (4 digit)',
        answer: '1945',
        explanation: 'Pancasila dirumuskan dalam sidang BPUPKI pada tahun 1945.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a08',
        type: 'multiple-choice',
        question: 'Nilai yang tidak terkandung dalam Pancasila adalah ...',
        options: ['Liberalisme absolut', 'Ketuhanan', 'Kemanusiaan', 'Persatuan'],
        answer: 'Liberalisme absolut',
        explanation: 'Pancasila tidak menganut liberalisme absolut yang menitikberatkan kebebasan tanpa batas individu.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-a09',
        type: 'true-false',
        question: 'Kepala banteng adalah lambang sila ke-4 Pancasila',
        answer: 'true',
        explanation: 'Sila ke-4 "Kerakyatan yang Dipimpin oleh Hikmat Kebijaksanaan dalam Permusyawaratan/Perwakilan" dilambangkan dengan kepala banteng.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a10',
        type: 'multiple-choice',
        question: 'Tanggal 1 Juni diperingati sebagai ...',
        options: ['Hari Lahir Pancasila', 'Hari Kemerdekaan', 'Hari Konstitusi', 'Hari Pahlawan'],
        answer: 'Hari Lahir Pancasila',
        explanation: '1 Juni 1945 adalah saat Soekarno berpidato mengusulkan nama Pancasila, sehingga diperingati sebagai Hari Lahir Pancasila.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-a11',
        type: 'multiple-choice',
        question: 'Rantai emas adalah lambang sila ke berapa dalam Pancasila?',
        options: ['Ke-2', 'Ke-1', 'Ke-3', 'Ke-4'],
        answer: 'Ke-2',
        explanation: 'Rantai emas melambangkan sila ke-2 "Kemanusiaan yang Adil dan Beradab", merepresentasikan hubungan manusia.',
        points: 10,
        difficulty: 'easy',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 2: UUD 1945 (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'pkn-b01',
        type: 'multiple-choice',
        question: 'Pasal berapakah yang mengatur tentang hak atas pekerjaan dan penghidupan layak?',
        options: ['Pasal 27 ayat 2', 'Pasal 27 ayat 1', 'Pasal 29', 'Pasal 30'],
        answer: 'Pasal 27 ayat 2',
        explanation: 'Pasal 27 ayat (2) UUD 1945: "Tiap-tiap warga negara berhak atas pekerjaan dan penghidupan yang layak bagi kemanusiaan."',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b02',
        type: 'true-false',
        question: 'Pembukaan UUD 1945 terdiri atas 4 alinea',
        answer: 'true',
        explanation: 'Pembukaan UUD 1945 memang terdiri atas empat alinea yang masing-masing memiliki makna mendalam.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b03',
        type: 'type-answer',
        question: 'UUD 1945 mengalami amandemen pertama pada tahun ... (4 digit)',
        answer: '1999',
        explanation: 'Amandemen UUD 1945 pertama terjadi pada tahun 1999, lalu 2000, 2001, dan 2002.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b04',
        type: 'multiple-choice',
        question: 'Dalam UUD 1945, anggaran pendapatan dan belanja negara diatur dalam pasal ...',
        options: ['Pasal 23', 'Pasal 22', 'Pasal 24', 'Pasal 25'],
        answer: 'Pasal 23',
        explanation: 'Pasal 23 UUD 1945 mengatur mengenai keuangan negara, termasuk APBN.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-b05',
        type: 'true-false',
        question: 'Pasal 30 UUD 1945 mengatur tentang pertahanan dan keamanan negara',
        answer: 'true',
        explanation: 'Pasal 30 UUD 1945 berisi ketentuan tentang usaha pertahanan dan keamanan negara.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b06',
        type: 'multiple-choice',
        question: 'Pasal berapa yang menyatakan bahwa bahasa negara adalah Bahasa Indonesia?',
        options: ['Pasal 36', 'Pasal 35', 'Pasal 37', 'Pasal 34'],
        answer: 'Pasal 36',
        explanation: 'Pasal 36 UUD 1945 menyatakan bahwa Bahasa Negara ialah Bahasa Indonesia.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b07',
        type: 'type-answer',
        question: 'Pasal berapakah UUD 1945 yang menyatakan bentuk negara Indonesia adalah Republik? Jawab angka saja.',
        answer: '1',
        explanation: 'Pasal 1 ayat (1): "Negara Indonesia ialah Negara Kesatuan, yang berbentuk Republik."',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b08',
        type: 'multiple-choice',
        question: 'Hak setiap warga negara untuk ikut serta dalam pembelaan negara diatur dalam UUD 1945 Pasal ...',
        options: ['27 ayat 3', '27 ayat 1', '28', '30'],
        answer: '27 ayat 3',
        explanation: 'Pasal 27 ayat (3) UUD 1945: "Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara."',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-b09',
        type: 'true-false',
        question: 'UUD 1945 merupakan hukum tertinggi di Indonesia (supremasi konstitusi)',
        answer: 'true',
        explanation: 'UUD 1945 berkedudukan sebagai hukum tertinggi dalam hierarki perundang-undangan Indonesia.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-b10',
        type: 'multiple-choice',
        question: 'Pasal 32 UUD 1945 mengatur tentang ...',
        options: ['Kebudayaan nasional', 'Pertahanan negara', 'Pendidikan nasional', 'Agama'],
        answer: 'Kebudayaan nasional',
        explanation: 'Pasal 32 mengatur tentang kebudayaan nasional Indonesia yang dikembangkan oleh negara.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-b11',
        type: 'type-answer',
        question: '28A sampai 28J UUD 1945 mengatur tentang ... (dua kata)',
        answer: 'Hak Asasi',
        explanation: 'Pasal 28A–28J UUD 1945 memuat ketentuan tentang Hak Asasi Manusia (HAM).',
        points: 15,
        difficulty: 'medium',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 3: SISTEM PEMERINTAHAN (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'pkn-c01',
        type: 'multiple-choice',
        question: 'Lembaga yang memiliki kewenangan membuat undang-undang di Indonesia adalah ...',
        options: ['DPR', 'Presiden', 'MA', 'MPR'],
        answer: 'DPR',
        explanation: 'DPR (Dewan Perwakilan Rakyat) merupakan lembaga legislatif yang berwenang membuat undang-undang.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c02',
        type: 'true-false',
        question: 'Wakil Presiden dipilih bersama Presiden dalam satu pasangan dalam Pemilu',
        answer: 'true',
        explanation: 'Presiden dan Wakil Presiden dipilih dalam satu pasangan calon oleh rakyat secara langsung.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c03',
        type: 'multiple-choice',
        question: 'Presiden dalam sistem presidensial Indonesia berkedudukan sebagai ...',
        options: ['Kepala negara sekaligus kepala pemerintahan', 'Hanya kepala negara', 'Hanya kepala pemerintahan', 'Pemimpin parlemen'],
        answer: 'Kepala negara sekaligus kepala pemerintahan',
        explanation: 'Dalam sistem presidensial Indonesia, presiden memegang dua peran sekaligus: kepala negara dan kepala pemerintahan.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c04',
        type: 'type-answer',
        question: 'Seorang presiden Indonesia maksimal menjabat berapa periode? (jawab angka)',
        answer: '2',
        explanation: 'Presiden dapat dipilih maksimal dua kali masa jabatan (2 × 5 tahun = 10 tahun).',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c05',
        type: 'multiple-choice',
        question: 'Mengapa Indonesia tidak menganut sistem parlementer?',
        options: ['Presiden tidak bertanggung jawab kepada parlemen', 'Parlemen tidak ada di Indonesia', 'Presiden dipilih oleh DPR', 'Indonesia menganut sistem federal'],
        answer: 'Presiden tidak bertanggung jawab kepada parlemen',
        explanation: 'Dalam sistem presidensial, presiden tidak bergantung pada kepercayaan parlemen karena dipilih langsung oleh rakyat.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-c06',
        type: 'true-false',
        question: 'Indonesia adalah negara kesatuan yang berbentuk republik',
        answer: 'true',
        explanation: 'Pasal 1 ayat (1) UUD 1945 menegaskan bahwa Indonesia adalah Negara Kesatuan yang berbentuk Republik.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c07',
        type: 'multiple-choice',
        question: 'MPR terdiri atas DPR dan ...',
        options: ['DPD', 'BPK', 'MA', 'MK'],
        answer: 'DPD',
        explanation: 'MPR (Majelis Permusyawaratan Rakyat) terdiri atas anggota DPR dan anggota DPD.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c08',
        type: 'true-false',
        question: 'MPR berwenang mengubah dan menetapkan UUD',
        answer: 'true',
        explanation: 'Pasal 3 UUD 1945: MPR berwenang mengubah dan menetapkan Undang-Undang Dasar.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c09',
        type: 'multiple-choice',
        question: 'Sistem otonomi daerah di Indonesia berarti ...',
        options: ['Daerah diberi kewenangan mengurus urusan sendiri', 'Daerah bebas membuat undang-undang', 'Daerah tidak perlu mengikuti pemerintah pusat', 'Daerah memiliki angkatan bersenjata sendiri'],
        answer: 'Daerah diberi kewenangan mengurus urusan sendiri',
        explanation: 'Otonomi daerah berarti pemerintah daerah diberi kewenangan untuk mengatur dan mengurus urusan pemerintahan sendiri.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-c10',
        type: 'type-answer',
        question: 'DPD singkatan dari Dewan Perwakilan ... (satu kata)',
        answer: 'Daerah',
        explanation: 'DPD adalah Dewan Perwakilan Daerah, lembaga legislatif yang mewakili kepentingan daerah.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-c11',
        type: 'multiple-choice',
        question: 'Menteri negara dalam kabinet Indonesia diangkat dan diberhentikan oleh ...',
        options: ['Presiden', 'DPR', 'MPR', 'Mahkamah Agung'],
        answer: 'Presiden',
        explanation: 'Dalam sistem presidensial, presiden berwenang mengangkat dan memberhentikan para menteri (kabinet).',
        points: 10,
        difficulty: 'easy',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 4: HAK & KEWAJIBAN (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'pkn-d01',
        type: 'multiple-choice',
        question: 'Berikut yang merupakan hak warga negara adalah ...',
        options: ['Mendapat perlindungan hukum', 'Membayar pajak', 'Mempertahankan negara', 'Menaati peraturan'],
        answer: 'Mendapat perlindungan hukum',
        explanation: 'Mendapat perlindungan hukum adalah hak warga negara. Membayar pajak, mempertahankan negara, dan menaati peraturan adalah kewajiban.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d02',
        type: 'true-false',
        question: 'Kewajiban membayar pajak diatur dalam Pasal 23A UUD 1945',
        answer: 'true',
        explanation: 'Pasal 23A UUD 1945 menyatakan bahwa pajak dan pungutan lain yang bersifat memaksa diatur dengan undang-undang.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d03',
        type: 'multiple-choice',
        question: 'HAM (Hak Asasi Manusia) bersifat ...',
        options: ['Universal dan tidak dapat dicabut', 'Hanya berlaku di negara demokrasi', 'Ditetapkan oleh pemerintah', 'Berlaku jika disetujui parlemen'],
        answer: 'Universal dan tidak dapat dicabut',
        explanation: 'HAM bersifat universal (berlaku untuk semua manusia) dan tidak dapat dicabut oleh siapapun.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-d04',
        type: 'type-answer',
        question: 'Komnas HAM singkatan dari Komisi Nasional Hak Asasi ... (satu kata)',
        answer: 'Manusia',
        explanation: 'Komnas HAM adalah Komisi Nasional Hak Asasi Manusia, lembaga yang bertugas mengkaji dan menyelidiki pelanggaran HAM.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d05',
        type: 'true-false',
        question: 'Hak dan kewajiban warga negara harus dilaksanakan secara seimbang',
        answer: 'true',
        explanation: 'Prinsip keseimbangan hak dan kewajiban adalah dasar kehidupan berbangsa yang harmonis.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d06',
        type: 'multiple-choice',
        question: 'Diskriminasi terhadap siapapun bertentangan dengan sila Pancasila ke ...',
        options: ['2', '1', '3', '5'],
        answer: '2',
        explanation: 'Sila ke-2 "Kemanusiaan yang Adil dan Beradab" menegaskan penghormatan terhadap HAM dan larangan diskriminasi.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-d07',
        type: 'multiple-choice',
        question: 'Kewajiban membela negara diatur dalam UUD 1945 Pasal ...',
        options: ['27 ayat 3', '27 ayat 1', '28', '30 ayat 1'],
        answer: '27 ayat 3',
        explanation: 'Pasal 27 ayat (3): "Setiap warga negara berhak dan wajib ikut serta dalam upaya pembelaan negara."',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d08',
        type: 'true-false',
        question: 'Pemenuhan hak warga negara adalah tanggung jawab negara/pemerintah',
        answer: 'true',
        explanation: 'Negara berkewajiban memenuhi, menghormati, dan melindungi hak-hak warga negaranya.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-d09',
        type: 'multiple-choice',
        question: 'Generasi muda Indonesia berkewajiban untuk ...',
        options: ['Menjaga persatuan dan kesatuan bangsa', 'Mengikuti budaya asing sepenuhnya', 'Menentang kebijakan pemerintah', 'Mengabaikan sejarah bangsa'],
        answer: 'Menjaga persatuan dan kesatuan bangsa',
        explanation: 'Sebagai generasi penerus, kewajiban menjaga persatuan dan kesatuan bangsa sesuai dengan nilai Pancasila sila ke-3.',
        points: 15,
        difficulty: 'medium',
    },

    // ══════════════════════════════════════════════════════════════
    // === BANK SOAL LEVEL 5: LEMBAGA & DEMOKRASI (pool tambahan) ===
    // ══════════════════════════════════════════════════════════════
    {
        id: 'pkn-e01',
        type: 'multiple-choice',
        question: 'Komisi Yudisial berwenang mengawasi perilaku ...',
        options: ['Hakim', 'Polisi', 'Jaksa', 'Menteri'],
        answer: 'Hakim',
        explanation: 'Komisi Yudisial bertugas mengawasi perilaku hakim dan menjaga kehormatan serta martabat hakim.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e02',
        type: 'true-false',
        question: 'Pemilu di Indonesia dilaksanakan setiap 5 tahun sekali',
        answer: 'true',
        explanation: 'Pemilu legislatif dan presiden dilaksanakan setiap 5 tahun sekali sesuai UUD 1945.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e03',
        type: 'multiple-choice',
        question: 'Badan Pemeriksa Keuangan (BPK) berwenang memeriksa ...',
        options: ['Pengelolaan keuangan negara', 'Pelaksanaan pemilu', 'Pelanggaran HAM', 'Sengketa pemilu'],
        answer: 'Pengelolaan keuangan negara',
        explanation: 'BPK bertugas memeriksa pengelolaan dan tanggung jawab tentang keuangan negara.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e04',
        type: 'type-answer',
        question: 'Lembaga yang menangani sengketa hasil Pemilu di Indonesia adalah MK atau ... Jawab: MK',
        answer: 'MK',
        explanation: 'Mahkamah Konstitusi (MK) berwenang mengadili sengketa hasil pemilihan umum.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e05',
        type: 'true-false',
        question: 'Indonesia menganut sistem multipartai dalam Pemilu',
        answer: 'true',
        explanation: 'Indonesia menganut sistem multipartai dimana banyak partai politik dapat berpartisipasi dalam Pemilu.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e06',
        type: 'multiple-choice',
        question: 'Tugas utama Mahkamah Konstitusi (MK) adalah ...',
        options: ['Menguji UU terhadap UUD', 'Mengadili kasus pidana', 'Membuat undang-undang', 'Mengawasi keuangan negara'],
        answer: 'Menguji UU terhadap UUD',
        explanation: 'MK berwenang menguji undang-undang terhadap UUD 1945 (judicial review).',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-e07',
        type: 'multiple-choice',
        question: 'Demokrasi Pancasila mengutamakan ...',
        options: ['Musyawarah untuk mufakat', 'Suara terbanyak mutlak', 'Keputusan individu', 'Hak minoritas saja'],
        answer: 'Musyawarah untuk mufakat',
        explanation: 'Demokrasi Pancasila mengutamakan musyawarah untuk mencapai mufakat, bukan sekadar voting.',
        points: 10,
        difficulty: 'easy',
    },
    {
        id: 'pkn-e08',
        type: 'true-false',
        question: 'Partai politik yang lolos ambang batas parlemen (parliamentary threshold) berhak mendapatkan kursi DPR',
        answer: 'true',
        explanation: 'Hanya partai yang memenuhi parliamentary threshold yang berhak mendapatkan kursi DPR.',
        points: 15,
        difficulty: 'medium',
    },
    {
        id: 'pkn-e09',
        type: 'multiple-choice',
        question: 'Asas LUBER JURDIL pada Pemilu, huruf "R" singkatan dari ...',
        options: ['Rahasia', 'Resmi', 'Rasional', 'Riil'],
        answer: 'Rahasia',
        explanation: 'LUBER JURDIL = Langsung, Umum, Bebas, Rahasia, Jujur, Adil. "R" adalah Rahasia.',
        points: 10,
        difficulty: 'easy',
    },
];
